name: Sync unstable from upstream

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch upstream/main and push to origin/unstable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git remote add upstream https://github.com/Vencord/Vesktop.git
          git fetch upstream main --depth=1 --force
          git push --force origin upstream/main:refs/heads/unstable
